'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>  _
Partial Friend NotInheritable Class AnnoTableNamesSettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As AnnoTableNamesSettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New AnnoTableNamesSettings()),AnnoTableNamesSettings)
    
    Public Shared ReadOnly Property [Default]() As AnnoTableNamesSettings
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("TaxCodeAnno")>  _
    Public Property TaxCodeAnnoFC() As String
        Get
            Return CType(Me("TaxCodeAnnoFC"),String)
        End Get
        Set
            Me("TaxCodeAnnoFC") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("LotsAnno")>  _
    Public Property LotsAnnoFC() As String
        Get
            Return CType(Me("LotsAnnoFC"),String)
        End Get
        Set
            Me("LotsAnnoFC") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("TaxlotNumberAnno")>  _
    Public Property TaxlotNumberAnnoFC() As String
        Get
            Return CType(Me("TaxlotNumberAnnoFC"),String)
        End Get
        Set
            Me("TaxlotNumberAnnoFC") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("TaxlotAcreageAnno")>  _
    Public Property TaxlotAcreageAnnoFC() As String
        Get
            Return CType(Me("TaxlotAcreageAnnoFC"),String)
        End Get
        Set
            Me("TaxlotAcreageAnnoFC") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anno0010scale")>  _
    Public Property Anno0010scaleFC() As String
        Get
            Return CType(Me("Anno0010scaleFC"),String)
        End Get
        Set
            Me("Anno0010scaleFC") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anno0020scale")>  _
    Public Property Anno0020scaleFC() As String
        Get
            Return CType(Me("Anno0020scaleFC"),String)
        End Get
        Set
            Me("Anno0020scaleFC") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anno0030scale")>  _
    Public Property Anno0030scaleFC() As String
        Get
            Return CType(Me("Anno0030scaleFC"),String)
        End Get
        Set
            Me("Anno0030scaleFC") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anno0040scale")>  _
    Public Property Anno0040scaleFC() As String
        Get
            Return CType(Me("Anno0040scaleFC"),String)
        End Get
        Set
            Me("Anno0040scaleFC") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anno0050scale")>  _
    Public Property Anno0050scaleFC() As String
        Get
            Return CType(Me("Anno0050scaleFC"),String)
        End Get
        Set
            Me("Anno0050scaleFC") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anno0100scale")>  _
    Public Property Anno0100scaleFC() As String
        Get
            Return CType(Me("Anno0100scaleFC"),String)
        End Get
        Set
            Me("Anno0100scaleFC") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anno0200scale")>  _
    Public Property Anno0200scaleFC() As String
        Get
            Return CType(Me("Anno0200scaleFC"),String)
        End Get
        Set
            Me("Anno0200scaleFC") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anno0400scale")>  _
    Public Property Anno0400scaleFC() As String
        Get
            Return CType(Me("Anno0400scaleFC"),String)
        End Get
        Set
            Me("Anno0400scaleFC") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anno0800scale")>  _
    Public Property Anno0800scaleFC() As String
        Get
            Return CType(Me("Anno0800scaleFC"),String)
        End Get
        Set
            Me("Anno0800scaleFC") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anno2000scale")>  _
    Public Property Anno2000scaleFC() As String
        Get
            Return CType(Me("Anno2000scaleFC"),String)
        End Get
        Set
            Me("Anno2000scaleFC") = value
        End Set
    End Property
End Class
