'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>  _
Partial Friend NotInheritable Class TaxLotSettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As TaxLotSettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New TaxLotSettings()),TaxLotSettings)
    
    Public Shared ReadOnly Property [Default]() As TaxLotSettings
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("County")>  _
    Public Property CountyField() As String
        Get
            Return CType(Me("CountyField"),String)
        End Get
        Set
            Me("CountyField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Town")>  _
    Public Property TownshipField() As String
        Get
            Return CType(Me("TownshipField"),String)
        End Get
        Set
            Me("TownshipField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("TownPart")>  _
    Public Property TownshipPartField() As String
        Get
            Return CType(Me("TownshipPartField"),String)
        End Get
        Set
            Me("TownshipPartField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("TownDir")>  _
    Public Property TownshipDirectionField() As String
        Get
            Return CType(Me("TownshipDirectionField"),String)
        End Get
        Set
            Me("TownshipDirectionField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Range")>  _
    Public Property RangeField() As String
        Get
            Return CType(Me("RangeField"),String)
        End Get
        Set
            Me("RangeField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("RangePart")>  _
    Public Property RangePartField() As String
        Get
            Return CType(Me("RangePartField"),String)
        End Get
        Set
            Me("RangePartField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("RangeDir")>  _
    Public Property RangeDirectionField() As String
        Get
            Return CType(Me("RangeDirectionField"),String)
        End Get
        Set
            Me("RangeDirectionField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SecNumber")>  _
    Public Property SectionNumberField() As String
        Get
            Return CType(Me("SectionNumberField"),String)
        End Get
        Set
            Me("SectionNumberField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Qtr")>  _
    Public Property QuarterSectionField() As String
        Get
            Return CType(Me("QuarterSectionField"),String)
        End Get
        Set
            Me("QuarterSectionField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("QtrQtr")>  _
    Public Property QuarterQuarterSectionField() As String
        Get
            Return CType(Me("QuarterQuarterSectionField"),String)
        End Get
        Set
            Me("QuarterQuarterSectionField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("ORMapNum")>  _
    Public Property OrmapMapNumberField() As String
        Get
            Return CType(Me("OrmapMapNumberField"),String)
        End Get
        Set
            Me("OrmapMapNumberField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("ORTaxlot")>  _
    Public Property OrmapTaxlotField() As String
        Get
            Return CType(Me("OrmapTaxlotField"),String)
        End Get
        Set
            Me("OrmapTaxlotField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("MapNumber")>  _
    Public Property MapNumberField() As String
        Get
            Return CType(Me("MapNumberField"),String)
        End Get
        Set
            Me("MapNumberField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Taxlot")>  _
    Public Property TaxlotField() As String
        Get
            Return CType(Me("TaxlotField"),String)
        End Get
        Set
            Me("TaxlotField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("MapTaxlot")>  _
    Public Property MapTaxlotField() As String
        Get
            Return CType(Me("MapTaxlotField"),String)
        End Get
        Set
            Me("MapTaxlotField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("TR^DSSQQ@@@@@")>  _
    Public Property MapTaxlotFormatMask() As String
        Get
            Return CType(Me("MapTaxlotFormatMask"),String)
        End Get
        Set
            Me("MapTaxlotFormatMask") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SpecialInt")>  _
    Public Property SpecialInterestField() As String
        Get
            Return CType(Me("SpecialInterestField"),String)
        End Get
        Set
            Me("SpecialInterestField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("MapSufNum")>  _
    Public Property MapSuffixNumberField() As String
        Get
            Return CType(Me("MapSuffixNumberField"),String)
        End Get
        Set
            Me("MapSuffixNumberField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("MapSufType")>  _
    Public Property MapSuffixTypeField() As String
        Get
            Return CType(Me("MapSuffixTypeField"),String)
        End Get
        Set
            Me("MapSuffixTypeField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("MapAcres")>  _
    Public Property MapAcresField() As String
        Get
            Return CType(Me("MapAcresField"),String)
        End Get
        Set
            Me("MapAcresField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anomaly")>  _
    Public Property AnomalyField() As String
        Get
            Return CType(Me("AnomalyField"),String)
        End Get
        Set
            Me("AnomalyField") = value
        End Set
    End Property
End Class
