'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>  _
Partial Friend NotInheritable Class TaxlotAcreageAnnoSettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As TaxlotAcreageAnnoSettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New TaxlotAcreageAnnoSettings()),TaxlotAcreageAnnoSettings)
    
    Public Shared ReadOnly Property [Default]() As TaxlotAcreageAnnoSettings
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0.8")>  _
    Public Property TextSize00120Scale() As String
        Get
            Return CType(Me("TextSize00120Scale"),String)
        End Get
        Set
            Me("TextSize00120Scale") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.6")>  _
    Public Property TextSize00240Scale() As String
        Get
            Return CType(Me("TextSize00240Scale"),String)
        End Get
        Set
            Me("TextSize00240Scale") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
    Public Property TextSize00360Scale() As String
        Get
            Return CType(Me("TextSize00360Scale"),String)
        End Get
        Set
            Me("TextSize00360Scale") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("3.2")>  _
    Public Property TextSize00480Scale() As String
        Get
            Return CType(Me("TextSize00480Scale"),String)
        End Get
        Set
            Me("TextSize00480Scale") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
    Public Property TextSize00600Scale() As String
        Get
            Return CType(Me("TextSize00600Scale"),String)
        End Get
        Set
            Me("TextSize00600Scale") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
    Public Property TextSize01200Scale() As String
        Get
            Return CType(Me("TextSize01200Scale"),String)
        End Get
        Set
            Me("TextSize01200Scale") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("16")>  _
    Public Property TextSize02400Scale() As String
        Get
            Return CType(Me("TextSize02400Scale"),String)
        End Get
        Set
            Me("TextSize02400Scale") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("32")>  _
    Public Property TextSize04800Scale() As String
        Get
            Return CType(Me("TextSize04800Scale"),String)
        End Get
        Set
            Me("TextSize04800Scale") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("48")>  _
    Public Property TextSize09600Scale() As String
        Get
            Return CType(Me("TextSize09600Scale"),String)
        End Get
        Set
            Me("TextSize09600Scale") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("160")>  _
    Public Property TextSize24000Scale() As String
        Get
            Return CType(Me("TextSize24000Scale"),String)
        End Get
        Set
            Me("TextSize24000Scale") = value
        End Set
    End Property
End Class
